#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${TEST_POSTGRES_DB};
    CREATE USER ${TEST_POSTGRES_USER} WITH PASSWORD '${TEST_POSTGRES_PASSWORD}';
    GRANT ALL ON DATABASE ${TEST_POSTGRES_DB} TO ${TEST_POSTGRES_USER};
EOSQL

# Grant schema permissions (required for PG15+ to allow CREATE TABLE)
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "${TEST_POSTGRES_DB}" <<-EOSQL
    ALTER SCHEMA public OWNER TO ${TEST_POSTGRES_USER};
EOSQL
