import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const DIR = dirname(fileURLToPath(import.meta.url));
const PKG = join(DIR, '..', 'node_modules', '@shikijs', 'langs-precompiled', 'dist');
const OUT = join(DIR, '..', 'core', 'utils');

if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });

// Read language names from index.mjs
const indexSrc = readFileSync(join(PKG, 'index.mjs'), 'utf-8');
const langMatch = indexSrc.match(/export const languageNames = (\[[^\]]+\])/);
if (!langMatch) throw new Error('Could not find languageNames in index.mjs');
var languageNames = JSON.parse(langMatch[1]);

// Keep only commonly used languages for a dev blog
var KEEP_LANGS = new Set([
  'javascript', 'typescript', 'jsx', 'tsx',
  'python', 'r', 'c', 'java', 'csharp', 'go', 'rust', 'cpp',
  'html', 'css', 'scss', 'sql', 'yaml', 'json', 'jsonc',
  'bash', 'shellscript', 'shellsession', 'markdown',
  'diff', 'docker', 'php', 'ruby', 'swift', 'kotlin', 'lua',
  'xml', 'toml', 'powershell', 'graphql', 'make',
  'terraform',
]);

languageNames = languageNames.filter(function (id) { return KEEP_LANGS.has(id); });

function toVarName(langId) {
  // e.g., "angular-html" -> "angularHtml", "c++" is not valid, but shiki uses "cpp"
  return langId.replace(/[-.](.)/g, (_, c) => c.toUpperCase());
}

function toDisplayName(langId) {
  const overrides = {
    abap: 'ABAP',
    apl: 'APL',
    awk: 'AWK',
    c: 'C',
    csharp: 'C#',
    cpp: 'C++',
    css: 'CSS',
    dart: 'Dart',
    diff: 'Diff',
    docker: 'Docker',
    dotenv: '.env',
    elisp: 'Emacs Lisp',
    fsharp: 'F#',
    gitCommit: 'Git Commit',
    glsl: 'GLSL',
    gnuplot: 'Gnuplot',
    go: 'Go',
    gdscript: 'GDScript',
    gdshader: 'GDShader',
    gdresource: 'GDResource',
    html: 'HTML',
    http: 'HTTP',
    ini: 'INI',
    java: 'Java',
    json: 'JSON',
    json5: 'JSON5',
    jsonc: 'JSON with Comments',
    jsonl: 'JSON Lines',
    jsx: 'JSX',
    kotlin: 'Kotlin',
    kusto: 'Kusto',
    less: 'Less',
    lua: 'Lua',
    make: 'Makefile',
    markdown: 'Markdown',
    mdx: 'MDX',
    perl6: 'Perl 6',
    php: 'PHP',
    plsql: 'PL/SQL',
    postcss: 'PostCSS',
    powershell: 'PowerShell',
    qml: 'QML',
    r: 'R',
    regexp: 'RegExp',
    rst: 'reStructuredText',
    sass: 'Sass',
    scss: 'SCSS',
    shaderlab: 'ShaderLab',
    shellscript: 'Shell Script',
    sql: 'SQL',
    sshConfig: 'SSH Config',
    stylus: 'Stylus',
    svg: 'SVG',
    swift: 'Swift',
    systemVerilog: 'SystemVerilog',
    toml: 'TOML',
    tsx: 'TSX',
    typespec: 'TypeSpec',
    typst: 'Typst',
    vb: 'Visual Basic',
    vhdl: 'VHDL',
    viml: 'VimL',
    vue: 'Vue',
    wasm: 'WebAssembly',
    wgsl: 'WGSL',
    xml: 'XML',
    yaml: 'YAML',
    zig: 'Zig',
  };
  if (overrides[langId]) return overrides[langId];
  // General: capitalize first letter, replace hyphens/dots with spaces
  return langId
    .split(/[-.]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

// Build alias map from dist files
const aliasMap = {};
const allFiles = [];

const { readdirSync } = await import('fs');
const files = readdirSync(PKG).filter((f) => f.endsWith('.mjs') && f !== 'index.mjs');

for (const f of files) {
  const src = readFileSync(join(PKG, f), 'utf-8');
  const lines = src.split('\n');
  const langId = f.replace(/\.mjs$/, '');
  allFiles.push(langId);
  // Check if alias
  const aliasMatch = lines[0]?.match(/^\/\* Alias (\S+) for (\S+) \*\//);
  if (aliasMatch) {
    const aliasName = aliasMatch[1];
    const targetLang = aliasMatch[2];
    aliasMap[langId] = targetLang;
  }
  // Check second line for re-export
  const reexportMatch = lines.find((l) => l.match(/export \{ default \} from '\.\/(.+)\.mjs'/));
  if (reexportMatch && !aliasMap[langId]) {
    aliasMap[langId] = reexportMatch[1];
  }
}

// Build lang to file mapping: resolve aliases to their primary
function resolveAlias(id) {
  const visited = new Set();
  let current = id;
  while (aliasMap[current] && !visited.has(current)) {
    visited.add(current);
    current = aliasMap[current];
  }
  return current;
}

// Generate shiki-highlighter.js
function generateHighlighter() {
  const imports = [];
  const langEntries = [];

  for (const langId of languageNames) {
    const primaryFile = resolveAlias(langId);
    const varName = 'lang_' + toVarName(langId);
    imports.push(`import ${varName} from '@shikijs/langs-precompiled/${primaryFile}';`);
    langEntries.push(`  ${JSON.stringify(langId)}: () => Promise.resolve(${varName}),`);
  }

  const content = `// Auto-generated by tools/generate-langs.mjs — do not edit manually
import { createBundledHighlighter } from '@shikijs/core';
import { createJavaScriptRegexEngine } from '@shikijs/engine-javascript';
${imports.join('\n')}
import nord from '@shikijs/themes/nord';
import monokai from '@shikijs/themes/monokai';
import oneDarkPro from '@shikijs/themes/one-dark-pro';
import catppuccinMocha from '@shikijs/themes/catppuccin-mocha';
import draculaSoft from '@shikijs/themes/dracula-soft';
import githubDark from '@shikijs/themes/github-dark';
import githubLight from '@shikijs/themes/github-light';

const plaintextLang = {
  name: 'plaintext',
  scopeName: 'text.plain',
  patterns: [],
  repository: {},
};

const ALL_THEMES = {
  'nord': () => Promise.resolve(nord),
  'monokai': () => Promise.resolve(monokai),
  'one-dark-pro': () => Promise.resolve(oneDarkPro),
  'catppuccin-mocha': () => Promise.resolve(catppuccinMocha),
  'dracula-soft': () => Promise.resolve(draculaSoft),
  'github-dark': () => Promise.resolve(githubDark),
  'github-light': () => Promise.resolve(githubLight),
};

const LANG_THEME_MAP = {
  javascript: 'nord',
  typescript: 'nord',
  jsx: 'nord',
  tsx: 'nord',
  python: 'monokai',
  r: 'monokai',
  c: 'one-dark-pro',
  java: 'one-dark-pro',
  csharp: 'one-dark-pro',
  go: 'one-dark-pro',
  rust: 'one-dark-pro',
  cpp: 'one-dark-pro',
  html: 'catppuccin-mocha',
  css: 'catppuccin-mocha',
  scss: 'catppuccin-mocha',
  sql: 'dracula-soft',
  yaml: 'dracula-soft',
  json: 'dracula-soft',
};

function themeForLang(lang) {
  return LANG_THEME_MAP[lang] || 'github-dark';
}

const highlighterFactory = createBundledHighlighter({
  langs: {
    'plaintext': () => Promise.resolve(plaintextLang),\n${langEntries.join('\n')}
  },
  themes: ALL_THEMES,
  engine: () => createJavaScriptRegexEngine(),
});

async function createHighlighter(options) {
  const allThemeNames = Object.keys(ALL_THEMES);
  const highlighter = await highlighterFactory({
    ...options,
    themes: allThemeNames,
  });
  const originalCodeToTokens = highlighter.codeToTokens.bind(highlighter);
  highlighter.codeToTokens = (code, opts = {}) => {
    const theme = themeForLang(opts.lang || 'plaintext');
    return originalCodeToTokens(code, { ...opts, theme });
  };
  return highlighter;
}

export default createHighlighter;
`;

  writeFileSync(join(OUT, 'shiki-highlighter.js'), content);
  console.log(`Generated shiki-highlighter.js with ${languageNames.length} languages`);
}

// Generate supported-languages.js
function generateSupportedLanguages() {
  const entries = [];

  for (const langId of languageNames) {
    const displayName = toDisplayName(langId);
    entries.push(`  ${JSON.stringify(langId)}: { name: ${JSON.stringify(displayName)} },`);
  }

  const content = `// Auto-generated by tools/generate-langs.mjs — do not edit manually

const SUPPORTED_LANGUAGES = {
  "plaintext": { name: "Plain Text" },\n${entries.join('\n')}
};

export default SUPPORTED_LANGUAGES;
`;

  writeFileSync(join(OUT, 'supported-languages.js'), content);
  console.log(`Generated supported-languages.js with ${languageNames.length} entries`);
}

generateHighlighter();
generateSupportedLanguages();
