"""Unit tests for template helper functions (filters, context processors)."""

from markupsafe import Markup

from src.infrastructure.input_adapters.template_helpers import nl2br_filter


class TestNl2brFilter:
    """Unit tests for the nl2br Jinja2 filter."""

    def test_escapes_html_tags(self):
        """Verify <script> tags are escaped and not rendered as HTML."""
        result = nl2br_filter("<script>alert('xss')</script>")
        assert "&lt;script&gt;" in result
        assert "<script>" not in result

    def test_converts_newlines_to_br(self):
        """Verify newlines are converted to <br> tags."""
        result = nl2br_filter("line1\nline2")
        assert "line1<br>\nline2" in result

    def test_handles_multiple_newlines(self):
        """Verify multiple consecutive newlines each produce a <br>."""
        result = nl2br_filter("a\n\nb")
        assert str(result).count("<br>") == 2

    def test_returns_empty_for_none(self):
        """Verify None input returns an empty string."""
        assert nl2br_filter(None) == ""

    def test_returns_empty_for_empty_string(self):
        """Verify empty string input returns an empty string."""
        assert nl2br_filter("") == ""

    def test_returns_markup_instance(self):
        """Verify the result is a Markup instance (safe HTML)."""
        assert isinstance(nl2br_filter("test"), Markup)

    def test_does_not_escape_generated_br(self):
        """Verify <br> tags generated by the filter are not double-escaped."""
        result = nl2br_filter("hello\nworld")
        assert "<br>" in str(result)

    def test_handles_text_without_newlines(self):
        """Verify plain text without newlines is returned unchanged."""
        assert nl2br_filter("hello world") == "hello world"

    def test_escapes_ampersands(self):
        """Verify ampersands are properly escaped to &amp;."""
        result = nl2br_filter("a & b")
        assert "&amp;" in result

    def test_escapes_quotes(self):
        """Verify double quotes are properly escaped."""
        result = nl2br_filter('say "hello"')
        assert "&#34;" in result
        assert '"' not in str(result)

    def test_mixed_content_with_newlines_and_html(self):
        """Verify mixed HTML and newlines are correctly escaped with <br> tags."""
        result = nl2br_filter("<b>bold</b>\nnext line")
        assert "&lt;b&gt;bold&lt;/b&gt;" in result
        assert "<br>" in str(result)
        assert "<b>" not in str(result)
